In [1]:
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer
from nltk.tokenize import word_tokenize
import re
import string
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.linear_model import SGDClassifier
from sklearn import metrics
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
import matplotlib as mlp
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import cross_val_score
from sklearn.neural_network import MLPClassifier

Reading original file

In [2]:
df1 = pd.read_excel('training-Obama-Romney-tweets.xlsx', sheetname = 'Obama')
inputFrame = df1
inputFrame.dropna(inplace = True)
print('Total number of tweets:'+str(len(inputFrame)))
print('top few tweets:')
inputFrame.head()

Total number of tweets:7182
top few tweets:


date            time  \
0  2012-10-16 00:00:00  10:28:53-05:00   
1  2016-12-10 00:00:00  10:09:00-05:00   
2  2012-10-16 00:00:00  10:04:30-05:00   
3  2012-10-16 00:00:00  10:00:36-05:00   
4  2012-10-16 00:00:00  09:50:08-05:00   

                                     Anootated tweet Class  
0  Kirkpatrick, who wore a baseball cap embroider...     0  
1  Question: If <e>Romney</e> and <e>Obama</e> ha...     2  
2  #<e>obama</e> debates that Cracker Ass Cracker...     1  
3  RT @davewiner Slate: Blame <e>Obama</e> for fo...     2  
4  @Hollivan @hereistheanswer  Youre missing the ...     0

Preprocessing (cleaning the tweets)

In [3]:
inputFrame_test = inputFrame.copy()
inputFrame_test['Class'] = inputFrame_test['Class'].astype(str) 
inputFrame1 = inputFrame_test[inputFrame_test.Class == '1']
inputFrame2 = inputFrame_test[inputFrame_test.Class == '-1']
inputFrame3 = inputFrame_test[inputFrame_test.Class == '0']
inputFrame = pd.concat([inputFrame1, inputFrame2, inputFrame3])
tweetProcessFrame = inputFrame.copy()

In [4]:
# Cleaning tweets

pwords,words=None, None

with open("positive-words.txt") as f:
    pwords = [el.strip() for el in f.readlines()]
with open("negative-words.txt") as f:
    nwords = [el.strip() for el in f.readlines()]

stop_words = set(stopwords.words('english'))
stemmer = SnowballStemmer("english")

emoticons_dict = {}
def populateEmoticonsDict():
    fileHandler = open('EmoticonsWithPolarity.txt', 'r')
    for line in fileHandler:
        emoticon_list = line[:-1].split(' ')
        sentiment = emoticon_list[-1]
        emoticon_list = emoticon_list[:-1]
        for emoticon in emoticon_list:
            emoticons_dict[emoticon] = sentiment
populateEmoticonsDict()

def replace(tweet,words,replacement):
    li = []
    for word in tweet:
        if word in words:
            li.append(replacement)
        else:
            li.append(word)
    return li

def processTweet(tweet):
    emotionFreeTweet = mapEmoticons(tweet)
    tagFreeTweet = removeTags(emotionFreeTweet)
    lowerCaseTweet = tagFreeTweet.lower()
    ptweet = replace(lowerCaseTweet.split(' '),pwords,'positive')
    ntweet = replace(ptweet,nwords,'negative')
    t = ' '.join(ntweet)
    puncFreeTweet = removePunctuations(t)
    stopFreeTweet = removeStopWords(puncFreeTweet, stop_words)
    stemmedTweet = stemWords(stopFreeTweet)
    return stemmedTweet

def stemWords(tweet):
    return [stemmer.stem(t) for t in tweet]

def mapEmoticons(tweet):
    list_words = tweet.split(' ')
    newtweet = ""
    for word in list_words:
        if word in emoticons_dict:
            newtweet = newtweet + ' ' + emoticons_dict.get(word) 
        else:
            newtweet = newtweet + ' ' + word
    return newtweet
    

def removeTags(tweet):
    cleanr = re.compile('(</?[a-zA-Z]+>|https?:\/\/[^\s]*|(^|\s)RT(\s|$)|@[^\s]+|\d+)')
    cleantext = re.sub(cleanr, ' weblink ', tweet)
    cleantext = re.sub('(?<=^|(?<=[^a-zA-Z0-9-_\.]))@([A-Za-z]+[A-Za-z0-9]+)',' usermention ',cleantext)
    cleantext = re.sub('[^\sa-zA-Z]+','',cleantext)
    cleantext = re.sub('\s+',' ',cleantext)
    return cleantext

def removePunctuations(tweet):
    exclude = set(string.punctuation) 
    t = ''
    for ch in tweet:
        if ch not in exclude:
            t+=ch
        else:
            t+=' '
    return tweet

def removeStopWords(tweet, stop_words):
    words_tokenize = word_tokenize(tweet)
    filtered_sentence = words_tokenize #[w for w in words_tokenize if w not in stop_words]
    return filtered_sentence #' '.join(filtered_sentence)

In [5]:
tweetProcessFrame.rename(columns={'date':'date','time':'time','Anootated tweet' : 'tweet','Class':'Class'},inplace = True)
tweetProcessFrame['tweet'] = tweetProcessFrame['tweet'].apply(processTweet)
del tweetProcessFrame['time']
del tweetProcessFrame['date']
def joinList1(tweetList):
    return " ".join(tweetList)

tweetProcessFrame['tweet'] = tweetProcessFrame['tweet'].apply(joinList1)
tweetProcessFrame1 = pd.DataFrame.drop_duplicates(tweetProcessFrame)
print('tweets after preprocessing')
tweetProcessFrame.head()

tweets after preprocessing


tweet Class
2   weblink obama weblink debat that cracker ass c...     1
25     still my posit mr presid weblink obama weblink     1
29  weblink you said so much posit thing about web...     1
32  weblink im a south african and i say weblink o...     1
44  okay weblink obama weblink it is time to put y...     1

spliting training and testing for 80-20 testing

In [6]:
#train, test = train_test_split(tweetProcessFrame, test_size = 0.2)
def splitTrainingData(df, train_data_prcnt=80):
    msk = np.random.rand(len(df)) < train_data_prcnt/100
    train = df[msk]
    test = df[~msk]
    return train, test
tweet_random_df = tweetProcessFrame1.copy()
for i in range(0, 50):
    split1_df, split2_df = splitTrainingData(tweet_random_df)
    tweet_random_df = pd.concat([split1_df, split2_df])
train, test = splitTrainingData(tweet_random_df)

In [7]:
train_data = train['tweet']
train_label = train['Class']
train_label = pd.to_numeric(train_label)

test_data = test['tweet']
test_class = test['Class']
test_class = pd.to_numeric(test_class)

In [8]:
count_vect = CountVectorizer(max_features = 4800, ngram_range=(1, 2))
X_train_counts = count_vect.fit_transform(train_data)

tf_transformer = TfidfTransformer(use_idf=True).fit(X_train_counts)
X_train_tf = tf_transformer.transform(X_train_counts)

Training Multinomial Naive Bayes

In [9]:
# mnbd = {   
#             'alpha':[(float)(el/1000) for el in range(0,100,1)], 
#             'fit_prior':(True,False)
#         }

clf = MultinomialNB(alpha= 0.99, fit_prior= True).fit(X_train_tf, train_label)
#GridSearchCV(MultinomialNB(),mnbd).fit(X_train_tf, train_label)
#clf.best_params_
# clf = MultinomialNB(alpha= 0.99, fit_prior= True).fit(X_train_tf, train_label)
X_test_counts = count_vect.transform(test_data)
X_test_tfidf = tf_transformer.transform(X_test_counts)
predicted = clf.predict(X_test_tfidf)

print('Test Accuracy:'+str(np.mean(predicted == test_class)))

print(metrics.classification_report(test_class, predicted))

print('Confusion Matrix:')
nb_confusion_matrix = metrics.confusion_matrix(test_class, predicted)
print(nb_confusion_matrix)

predicted_train = clf.predict(X_train_tf)
print('Train Accuracy:'+str(np.mean(predicted_train == train_label)))

Test Accuracy:0.568716094033
             precision    recall  f1-score   support

         -1       0.56      0.63      0.59       407
          0       0.51      0.50      0.51       373
          1       0.66      0.57      0.61       326

avg / total       0.57      0.57      0.57      1106

Confusion Matrix:
[[255 118  34]
 [124 188  61]
 [ 79  61 186]]
Train Accuracy:0.770477047705


Support Vector Machine (Linear SVC)

In [10]:
# parameterssvm = {'vect__ngram_range': [(1, 1), (1, 2)],
#               'vect__max_features': list(range(500,5500,100)),
#               'tfidf__use_idf': (True, False),
#               'clf__loss' : ['hinge', 'squared_hinge'],
#               'clf__penalty' : ['l2'],
#               'clf__C' : [i/10 for i in range(5,9)],
#               'clf__multi_class' : ['crammer_singer','ovr']
#              }

# text_clf_svm = Pipeline([('vect', CountVectorizer()),
#                     ('tfidf', TfidfTransformer()),
#                     ('clf', LinearSVC(random_state= 42, max_iter=10000))])
# text_clf_svm = text_clf_svm.fit(train_data,train_label)
# text_clf_svm = GridSearchCV(text_clf_svm,parameterssvm,n_jobs=-1).fit(train_data, train_label)
# text_clf_svm.best_params_

# {'clf__C': 0.5,
#  'clf__loss': 'hinge',
#  'clf__multi_class': 'ovr',
#  'clf__penalty': 'l2',
#  'tfidf__use_idf': True,
#  'vect__max_features': 4800,
#  'vect__ngram_range': (1, 2)}

text_clf_svm = Pipeline([('vect', CountVectorizer(max_features=4800,ngram_range=(1,2))),
                    ('tfidf', TfidfTransformer(use_idf=True)),
                    ('clf', LinearSVC(C=0.5,loss='hinge',multi_class='ovr',penalty='l2',random_state= 42, max_iter=10000))]).fit(train_data, train_label)

predicted_svm = text_clf_svm.predict(test_data)
print('Test Accuracy:'+str(np.mean(predicted_svm == test_class)))
print(metrics.classification_report(test_class, predicted_svm))

print('Confusion Matrix:')
linearSVM_confusion_matrix = metrics.confusion_matrix(test_class, predicted_svm)
print(linearSVM_confusion_matrix)

predicted_svm_train = text_clf_svm.predict(train_data)
print('Train Accuracy:'+str(np.mean(predicted_svm_train == train_label)))

Test Accuracy:0.591320072333
             precision    recall  f1-score   support

         -1       0.57      0.66      0.61       407
          0       0.57      0.50      0.53       373
          1       0.64      0.62      0.63       326

avg / total       0.59      0.59      0.59      1106

Confusion Matrix:
[[268  92  47]
 [121 185  67]
 [ 78  47 201]]
Train Accuracy:0.794329432943


Voting classifier

In [11]:
clf1 = MultinomialNB(alpha= 0.094, fit_prior= True)
clf2 = SGDClassifier(alpha=0.001,learning_rate='optimal',loss= 'epsilon_insensitive', penalty= 'l2',n_iter = 100, random_state=42)
clf3 = LinearSVC(C = 0.5, loss = 'hinge', random_state= 42)
clf4 = RandomForestClassifier(n_estimators = 22, class_weight = 'balanced_subsample', random_state = 42,criterion="gini")

eclf = Pipeline([('vect', CountVectorizer(max_features=4800,ngram_range=(1,2))),
                    ('tfidf', TfidfTransformer(use_idf= True)),
                    ('clf', VotingClassifier(estimators=[('mnb', clf1), ('sgd', clf2), ('svm', clf3), ('rf',clf4)], voting='hard'))])

eclf = eclf.fit(train_data,train_label)

p = eclf.predict(test_data)
print('Test Accuracy:'+str(np.mean(p==test_class)))
print(metrics.classification_report(test_class, p))

print('Confusion Matrix:')
voting_confusion_matrix = metrics.confusion_matrix(test_class,p)
print(voting_confusion_matrix)

predicted_eclf_train = eclf.predict(train_data)
print('Train Accuracy:'+str(np.mean(predicted_eclf_train == train_label)))

Test Accuracy:0.601265822785
             precision    recall  f1-score   support

         -1       0.57      0.71      0.63       407
          0       0.58      0.50      0.53       373
          1       0.68      0.59      0.63       326

avg / total       0.61      0.60      0.60      1106

Confusion Matrix:
[[288  84  35]
 [132 185  56]
 [ 83  51 192]]
Train Accuracy:0.823807380738


Other approaces tried

SGD Classifier

In [12]:
# parameterssgd = {'vect__ngram_range': [(1, 1), (1, 2)],
#               'vect__max_features': list(range(100,5000,500)),
#               'tfidf__use_idf': (True, False),
#               'clf__loss' : ['hinge', 'log', 'modified_huber', 'squared_hinge', 'perceptron', 'squared_loss', 'huber', 
#                              'epsilon_insensitive', 'squared_epsilon_insensitive'],
#               'clf__penalty' : ['l2', 'l1', 'elasticnet'],
#               'clf__learning_rate' : ['optimal','invscaling'],
#               'clf__alpha': [i/1000 for i in range(1,10)]
#              }
# text_clf = Pipeline([('vect', CountVectorizer()),
#                     ('tfidf', TfidfTransformer()),
#                     ('clf', SGDClassifier(n_iter = 100, eta0 = 0.0001, random_state=42))])
# text_clf = GridSearchCV(text_clf,parameterssgd,n_jobs=-1).fit(train_data, train_label)
# text_clf.best_params_

text_clf_sgd = Pipeline([('vect', CountVectorizer(max_features=5000,ngram_range=(1,2))),
                    ('tfidf', TfidfTransformer(use_idf= True)),
                    ('clf', SGDClassifier(alpha=0.001,learning_rate='optimal',loss= 'epsilon_insensitive'
                                          ,penalty= 'l2',n_iter = 100, random_state=42))]).fit(train_data, train_label)

predicted_sgd = text_clf_sgd.predict(test_data)
print('Test Accuracy:'+str(np.mean(predicted_sgd == test_class)))
print(metrics.classification_report(test_class, predicted_sgd))

print('Confusion Matrix:')
linearSGD_confusion_matrix = metrics.confusion_matrix(test_class, predicted_sgd)
print(linearSGD_confusion_matrix)

predicted_sgd_train = text_clf_sgd.predict(train_data)
print('Train Accuracy:'+str(np.mean(predicted_sgd_train == train_label)))

Test Accuracy:0.597649186257
             precision    recall  f1-score   support

         -1       0.57      0.70      0.63       407
          0       0.59      0.47      0.52       373
          1       0.64      0.62      0.63       326

avg / total       0.60      0.60      0.59      1106

Confusion Matrix:
[[285  78  44]
 [131 174  68]
 [ 80  44 202]]
Train Accuracy:0.763726372637


Random Forest

In [13]:
# parametersrf = {'vect__ngram_range': [(1, 1), (1, 2)],
#               'vect__max_features': list(range(500,5000,100)),
#               'tfidf__use_idf': (True, False),
#               'clf__criterion' : ['gini','entropy'],
#                 'clf__n_estimators' : list(range(2,25,10)),
#                 'clf__class_weight' : ['balanced_subsample']
#                 }

# text_clf_RandomForest = Pipeline([('vect', CountVectorizer()),
#                     ('tfidf', TfidfTransformer()),
#                     ('clf', RandomForestClassifier(random_state = 42))])
# text_clf_RandomForest = GridSearchCV(text_clf_RandomForest,parametersrf,n_jobs=-1).fit(train_data, train_label)
# text_clf_RandomForest.best_params_

text_clf_RandomForest = Pipeline([('vect', CountVectorizer(max_features = 4700,ngram_range=(1,2))),
                    ('tfidf', TfidfTransformer(use_idf=True)),
                    ('clf', RandomForestClassifier(random_state = 42,criterion="gini",class_weight='balanced_subsample'
                                                   ,n_estimators=22))])
text_clf_RandomForest = text_clf_RandomForest.fit(train_data, train_label)
# {'clf__class_weight': 'balanced_subsample',
#  'clf__criterion': 'gini',
#  'clf__n_estimators': 22,
#  'tfidf__use_idf': True,
#  'vect__max_features': 4700,
#  'vect__ngram_range': (1, 2)}
predicted_rf = text_clf_RandomForest.predict(test_data)
print('Test Accuracy:'+str(np.mean(predicted_rf == test_class)))
print(metrics.classification_report(test_class, predicted_rf))

print('Confusion Matrix:')
linearRF_confusion_matrix = metrics.confusion_matrix(test_class, predicted_rf)
print(linearRF_confusion_matrix)

predicted_rf_train = text_clf_RandomForest.predict(train_data)
print('Train Accuracy:'+str(np.mean(predicted_rf_train == train_label)))

Test Accuracy:0.553345388788
             precision    recall  f1-score   support

         -1       0.57      0.59      0.58       407
          0       0.52      0.57      0.54       373
          1       0.58      0.49      0.53       326

avg / total       0.56      0.55      0.55      1106

Confusion Matrix:
[[240 119  48]
 [ 94 213  66]
 [ 90  77 159]]
Train Accuracy:0.995274527453


Preparing Data for Cross Validation

In [14]:
combineFrameData = [train_data, test_data]
combineFrameLabel = [train_label, test_class]
combineTrainDataDF = pd.concat(combineFrameData)
combineTrainLabelDF = pd.concat(combineFrameLabel)
count_vect_kfold = CountVectorizer(max_features = 4800)
X_train_counts_kfold = count_vect.fit_transform(combineTrainDataDF)
tf_transformer_kfold = TfidfTransformer(use_idf=True).fit(X_train_counts_kfold)
X_train_tf_kfold = tf_transformer_kfold.transform(X_train_counts_kfold)

Cross Validation accuracy Naive Bayes

In [15]:
clf_nb_kfold = MultinomialNB(alpha = 0.099, fit_prior = True)
scores = cross_val_score(clf_nb_kfold, X_train_tf_kfold, combineTrainLabelDF, cv=10)
clf_nb_kfold = clf_nb_kfold.fit(X_train_tf_kfold, combineTrainLabelDF)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
print(scores)

Accuracy: 0.58 (+/- 0.04)
[ 0.55215827  0.55935252  0.59892086  0.57837838  0.57477477  0.58918919
  0.58918919  0.61441441  0.59205776  0.55153707]


Cross Validation Accuracy Linear SVM

In [16]:
clf_lsvm_kfold = LinearSVC(C = 0.5, loss = 'hinge', penalty='l2', random_state= 42, max_iter=10000)
scores_lsvm = cross_val_score(clf_lsvm_kfold, X_train_tf_kfold, combineTrainLabelDF, cv=10)
clf_lsvm_kfold = clf_lsvm_kfold.fit(X_train_tf_kfold, combineTrainLabelDF)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_lsvm.mean(), scores_lsvm.std() * 2))
print(scores_lsvm)

Accuracy: 0.61 (+/- 0.04)
[ 0.59532374  0.59352518  0.62589928  0.61801802  0.60900901  0.61801802
  0.62882883  0.62522523  0.58303249  0.57504521]


Cross Validation SGD

In [17]:
clf_sgd_kfold = SGDClassifier(alpha=0.001,learning_rate='optimal',loss= 'epsilon_insensitive', penalty= 'l2',n_iter = 100, random_state=42)
scores_sgd = cross_val_score(clf_sgd_kfold, X_train_tf_kfold, combineTrainLabelDF, cv=10)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_sgd.mean(), scores_sgd.std() * 2))
print(scores_sgd)

Accuracy: 0.60 (+/- 0.03)
[ 0.58992806  0.60431655  0.62410072  0.61261261  0.58738739  0.6036036
  0.61441441  0.61981982  0.59566787  0.56600362]


Cross Validation accuracy Random Forest

In [18]:
clf_randomForest_kfold = RandomForestClassifier(n_estimators = 22, class_weight = 'balanced_subsample', random_state = 42, criterion="gini")
scores_randomForest = cross_val_score(clf_randomForest_kfold, X_train_tf_kfold, combineTrainLabelDF, cv=10)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_randomForest.mean(), scores_randomForest.std() * 2))
print(scores_randomForest)

Accuracy: 0.57 (+/- 0.04)
[ 0.56115108  0.58633094  0.5647482   0.58918919  0.59279279  0.58558559
  0.52972973  0.56216216  0.54693141  0.55334539]


In [19]:
import pickle as pickle
with open('nb_dumped_classifier.pkl', 'wb') as fid:
    pickle.dump(clf, fid)  
with open('svm_dumped_classifier.pkl', 'wb') as fid:
    pickle.dump(text_clf_svm, fid) 
with open('voting_dumped_classifier.pkl', 'wb') as fid:
    pickle.dump(eclf, fid) 
# # load a classifier
# with open('svm_dumped_classifier_romney.pkl', 'rb') as fid:
#     gnb_loaded = pickle.load(fid)

In [25]:
df_test = pd.read_excel('testing-Obama-Romney-tweets.xlsx', sheetname = 'Obama')#, header=None)
df_test.columns = ['tweet','Class']
df_test['Class'] = df_test['Class'].astype(str) 
inputFrame1 = df_test[df_test.Class == '1']
inputFrame2 = df_test[df_test.Class == '-1']
inputFrame3 = df_test[df_test.Class == '0']
df_test = pd.concat([inputFrame1, inputFrame2, inputFrame3])
df_test['tweet'] = df_test['tweet'].apply(processTweet)
df_test['tweet'] = df_test['tweet'].apply(joinList1)

testcounts = count_vect.transform(df_test['tweet'])
test_tfidf = tf_transformer_kfold.transform(testcounts)

df_test.head()

tweet Class
2     weblink obama weblink has to maintain his prof...     1
11    weblink obama weblink went into the debat swin...     1
21    ditto i start weblink weblink year ago weblink...     1
36    i absolut posit weblink obama weblink s view i...     1
43    im agre complet with weblink obama weblink s s...     1
46    weblink obama weblink s weblink posit weblink ...     1
47    hahahahahaahahha weblink obama weblink s webli...     1
48    if you think the economi has gotten negat dure...     1
50    weblink obama weblink s weblink debat perform ...     1
51    i posit the fact that it not within weblink ob...     1
56    presid weblink obama weblink s weblink polici ...     1
57    posit weblink obama weblink s weblink defens o...     1
58    weblink obama weblink s weblink haircut weblin...     1
59    posit presid weblink obama weblink s extempora...     1
64    look at weblink obama weblink s weblink walk w...     1
66    irrroc weblink obama weblink s weblink spend w...     1
69    weblink obama weblink s on his posit weblink g...     1
71    the debat isnt even over and weblink obama web...     1
72    weblink obama weblink s weblink respons weblin...     1
75    posit weblink obama weblink s weblink respons ...     1
76    weblink obama weblink s weblink answer weblink...     1
78    jonshuman sure i bet he was my dad now has a p...     1
83    weblink weblink i posit weblink obama weblink ...     1
84    yes weblink obama weblink s weblink main focus...     1
90    but i know im weblink vote weblink for weblink...     1
96    weblink barackobama weblink ive got your back ...     1
100                 i posit weblink obama weblink truth     1
103   i negat when peopl say weblink obama weblink h...     1
109   i want my next boyfriend to weblink look webli...     1
113   yes weblink obama weblink is an idealist but h...     1
...                                                 ...   ...
2319  negat obamareagan pic weblink negat negat nega...     0
2320  negat when i hear about a terrorist negat nega...     0
2321  negat negat news energis weblink obama weblink...     0
2323  negat weblink weblink obama weblink come from ...     0
2327  negat i posit a weblink video weblink weblink ...     0
2335  negat what do all these celeb have in common w...     0
2336  negat is weblink obama weblink head to vega ag...     0
2338  negat hahaha weblink michell obama weblink sho...     0
2340  negat check out airhead actress in new proobam...     0
2341  negat posit i taught us histori student about ...     0
2342  negat weblink obama weblink masih pake bukanny...     0
2347  negat weblink obama weblink make educ a weblin...     0
2348  negat no hope except through god mike church s...     0
2350  negat weblink obama weblink campaign posit kno...     0
2351  negat weblink obama weblink say when i was web...     0
2353  negat weblink and they posit weblink obama web...     0
2355  negat negat bobbi jindal he dont do negat for ...     0
2358  negat has weblink obama weblink negat the huff...     0
2359  negat obama negat negat negat negat negat nega...     0
2360  negat weblink if true negat it might be due to...     0
2365  negat crowley let weblink obama weblink have l...     0
2366  negat weblink you do know that obama not in th...     0
2367  negat negat orang broccoli weblink obama webli...     0
2373  negat supremecourt agre to hear case on federa...     0
2377  negat negat on phish lotto x weblink email pos...     0
2380  negat thought there was an invas go on outsid ...     0
2381  negat weblink anoth christian universityetbu h...     0
2392  negat negat weblink pm weblink weblink gender ...     0
2397  negat weblink it leav out other black immigr o...     0
2400  negat rae sky negat my compani stock hit a web...     0

[1951 rows x 2 columns]

In [26]:
p = clf_nb_kfold.predict(test_tfidf)
xy = pd.to_numeric(df_test['Class'])
print('Test Accuracy:'+str(np.mean(p == xy)))

print(metrics.classification_report(xy, p))

print('Confusion Matrix:')
nb_confusion_matrix = metrics.confusion_matrix(xy, p)
print(nb_confusion_matrix)

Test Accuracy:0.556637621732
             precision    recall  f1-score   support

         -1       0.55      0.60      0.58       688
          0       0.53      0.54      0.53       681
          1       0.60      0.53      0.56       582

avg / total       0.56      0.56      0.56      1951

Confusion Matrix:
[[411 187  90]
 [199 368 114]
 [131 144 307]]


In [27]:
p = clf_lsvm_kfold.predict(test_tfidf)
xy = pd.to_numeric(df_test['Class'])
print('Test Accuracy:'+str(np.mean(p == xy)))

print(metrics.classification_report(xy, p))

print('Confusion Matrix:')
nb_confusion_matrix = metrics.confusion_matrix(xy, p)
print(nb_confusion_matrix)

Test Accuracy:0.59354177345
             precision    recall  f1-score   support

         -1       0.58      0.67      0.62       688
          0       0.58      0.56      0.57       681
          1       0.62      0.55      0.58       582

avg / total       0.59      0.59      0.59      1951

Confusion Matrix:
[[460 139  89]
 [196 380 105]
 [133 131 318]]


In [28]:
p = eclf.predict(df_test['tweet'])
xy = pd.to_numeric(df_test['Class'])
print('Test Accuracy:'+str(np.mean(p == xy)))

print(metrics.classification_report(xy, p))

print('Confusion Matrix:')
nb_confusion_matrix = metrics.confusion_matrix(xy, p)
print(nb_confusion_matrix)

Test Accuracy:0.581752947207
             precision    recall  f1-score   support

         -1       0.56      0.68      0.62       688
          0       0.58      0.54      0.56       681
          1       0.62      0.51      0.56       582

avg / total       0.59      0.58      0.58      1951

Confusion Matrix:
[[471 135  82]
 [218 365  98]
 [149 134 299]]
